cmake_minimum_required(VERSION 4.0)
project(Tidbits)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(src/beeper)
add_subdirectory(src/concepts)
add_subdirectory(src/crtp)
add_subdirectory(src/arbitrage)
add_subdirectory(src/stack_allocator)
add_subdirectory(src/double_ended_stack_allocator)
add_subdirectory(src/pool_allocator)
add_subdirectory(src/arena_allocator)
add_subdirectory(src/file_streaming)
add_subdirectory(src/lambda)
add_subdirectory(src/ecs)
add_subdirectory(src/overload)
add_subdirectory(src/memmove)
add_subdirectory(src/find_unique)
add_subdirectory(src/modules)
add_subdirectory(src/pattern_match)
add_subdirectory(src/remove_spaces)
add_subdirectory(src/reverse_string)
add_subdirectory(src/singleton)
add_subdirectory(src/multithreading_primitives)
add_subdirectory(src/perfect_forwarding)
add_subdirectory(src/variadic_template)
add_subdirectory(src/sparse_set)